//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.01 at 12:40:32 PM MST 
//


package xmlbinds;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for Files complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Files">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReadFolder" type="{}ReadFolder" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AssemblyFolder" type="{}AssemblyFolder" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Files", propOrder = {
    "readFolder",
    "assemblyFolder"
})
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-07-01T12:40:32-07:00", comments = "JAXB RI v2.2.8-b130911.1802")
public class Files {

    @XmlElement(name = "AlignmentFolder", required = true)
    protected List<AlignmentFolder> alignmentFolder;
    @XmlElement(name = "VCFFolder", required = true)
    protected List<VCFFolder> vcfFolder;
    @XmlElement(name = "ReadFolder")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-07-01T12:40:32-07:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected List<ReadFolder> readFolder;
    @XmlElement(name = "AssemblyFolder")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-07-01T12:40:32-07:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected List<AssemblyFolder> assemblyFolder;

    /**
     * Gets the value of the alignmentFolder property.
     *
     * @return
     *     possible object is
     *     {@link AlignmentFolder }
     *
     */
    public List<AlignmentFolder> getAlignmentFolder() {
        if( alignmentFolder == null){
            alignmentFolder = new ArrayList<AlignmentFolder>();
        }
        return this.alignmentFolder;
    }


    /**
     * Gets the value of the vcfFolder property.
     *
     * @return
     *     possible object is
     *     {@link VCFFolder }
     *
     */
    public List<VCFFolder> getVCFFolder() {
        if( vcfFolder == null ) {
            vcfFolder =  new ArrayList<VCFFolder>();
        }
            return this.vcfFolder;
    }

    /**
     * Gets the value of the readFolder property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the readFolder property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReadFolder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReadFolder }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-07-01T12:40:32-07:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public List<ReadFolder> getReadFolder() {
        if (readFolder == null) {
            readFolder = new ArrayList<ReadFolder>();
        }
        return this.readFolder;
    }

    /**
     * Gets the value of the assemblyFolder property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assemblyFolder property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssemblyFolder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AssemblyFolder }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-07-01T12:40:32-07:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public List<AssemblyFolder> getAssemblyFolder() {
        if (assemblyFolder == null) {
            assemblyFolder = new ArrayList<AssemblyFolder>();
        }
        return this.assemblyFolder;
    }

}
